version: "3"
services:
  mysql:
    image: bmalhotradocker/mysqlconsul
    container_name: mysql
    command: /script.sh
    network_mode: bridge
    ports:
      - "8306:3306"
  app:
    image: bmalhotradocker/phpconsul
    container_name: php
    depends_on:
      - mysql
    command: /script.sh
    network_mode: bridge
    ports:
      - "8080:80"